# Generated by Django 5.2.17 on 2026-09-07 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(db_index=True, max_length=50)),
                ('insured_name', models.CharField(max_length=120)),
                ('loss_date', models.DateField(db_index=True)),
                ('date_notified', models.DateField(db_index=True)),
                ('loss_nature', models.CharField(choices=[('fire', 'Fire'), ('theft', 'Theft'), ('flood', 'Flood'), ('motor', 'Motor'), ('liability', 'Liability'), ('medical', 'Medical'), ('marine', 'Marine'), ('other', 'Other')], max_length=20)),
                ('currency', models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], db_index=True, max_length=3)),
                ('estimated_loss_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_notified', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('estimated_loss_amount__gt', 0)), name='claim_estimated_loss_positive'), models.CheckConstraint(condition=models.Q(('approved_amount__isnull', True), ('approved_amount__gt', 0), _connector='OR'), name='claim_approved_amount_positive_or_null'), models.CheckConstraint(condition=models.Q(('date_notified__gte', models.F('loss_date'))), name='claim_notified_on_or_after_loss'), models.CheckConstraint(condition=models.Q(models.Q(('approved_amount__isnull', True), ('approved_at__isnull', True)), models.Q(('approved_amount__isnull', False), ('approved_at__isnull', False)), _connector='OR'), name='claim_approved_amount_and_at_together')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('amount_in_claim_currency', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='claims.claim')),
            ],
            options={
                'ordering': ['payment_date', 'id'],
                'indexes': [models.Index(fields=['claim', 'payment_date'], name='claims_paym_claim_i_f8bd05_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='payment_amount_nonzero'), models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='payment_rate_positive')],
            },
        ),
    ]
