# Generated by Django 5.2.17 on 2026-09-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='loss_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
